# Generated by Django 4.2.2 on 2024-07-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
    ]
