# Generated by Django 4.2.2 on 2024-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_forecast',
            field=models.CharField(choices=[('early', 'Early'), ('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
