# Generated by Django 4.2.2 on 2024-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_arrival_forecast_alter_flight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(default='A1', max_length=5),
        ),
    ]
